api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']

  formats:
    jsonld:   ['application/ld+json']
    jsonapi:  ['application/vnd.api+json']
    jsonhal:  ['application/hal+json']
    json:     ['application/json']
    html:     ['text/html']
